baseurl = "http://rayrshah.github.io/"
languageCode = "en-us"
title = "Ray Shah - Product Designer"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = true

[taxonomies]
  category = "categories"
  tag = "tags"
