baseurl = "http://rayrshah.github.io/public"
languageCode = "en-us"
title = "Ray Shah - Digital Product Designer"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = true
theme = "robust"

[params]
	AuthorName = "Ray Shah"
	SiteDesc = "Portfolio of Ray Shah"

[taxonomies]
  category = "categories"
  tag = "tags"
